package com.example.virtual_fridge;

import android.os.Parcel;
import android.os.Parcelable;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity(tableName = "kitchen_list_table")
public class KitchenItem implements Parcelable {

    // unique id, autogenerated
    @PrimaryKey(autoGenerate = true)
    public int id;

    @NonNull
    public String name;

    public float quantity;
    public String unit;
    public String type;
    public String expiryDate;
    public String location;

    // unused constructor
    @Ignore
    public KitchenItem(@NonNull String name) {
        this.name = name;
    }

    // used constructor
    public KitchenItem(@NonNull String name, float quantity, String unit, String expiryDate, String location, String type) {
        this.name = name;
        this.quantity = quantity;
        this.unit = unit;
        this.expiryDate = expiryDate;
        this.location = location;
        this.type = type;
    }

    public static final Creator<KitchenItem> CREATOR = new Creator<KitchenItem>() {
        @Override
        public KitchenItem createFromParcel(Parcel in) {
            return new KitchenItem(in);
        }

        @Override
        public KitchenItem[] newArray(int size) {
            return new KitchenItem[size];
        }
    };

    // Getters
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public float getQuantity() {
        return quantity;
    }

    public String getUnit() {
        return unit;
    }

    public String getType() {
        return type;
    }

    public String getExpiryDate() {
        return expiryDate;
    }

    public String getLocation() {
        return location;
    }

    // Setters
    public void setQuantity(float quantity) {
        this.quantity = quantity;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setExpiryDate(String expiryDate) {
        this.expiryDate = expiryDate;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    // Parcelable implementation methods
    @Override
    public int describeContents() {
        return 0;
    }

    protected KitchenItem(Parcel in) {
        id = in.readInt();
        name = in.readString();
        quantity = in.readFloat();
        unit = in.readString();
        type = in.readString();
        expiryDate = in.readString();
        location = in.readString();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(id);
        dest.writeString(name);
        dest.writeFloat(quantity);
        dest.writeString(unit);
        dest.writeString(type);
        dest.writeString(expiryDate);
        dest.writeString(location);
    }
}
